title: Shivam Parashar
logo: /Headshot.jpeg
description: Software Engineer | DevOps | Cloud Enthusiast
show_downloads: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
permalink: /
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
